
server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 'postgres'
    url: jdbc:postgresql://localhost:5432/guild
    username: 'postgres'
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
